name       : vice
version    : '3.4'
release    : 7
source     :
    - https://sourceforge.net/projects/vice-emu/files/releases/vice-3.4.tar.gz/download : 4bd00c1c63d38cd1fe01b90032834b52f774bc29e4b67eeb1e525b14fee07aeb
license    : GPL-2.0-or-later
component  : games.emulator
summary    : VICE, the multi-platform C64, C128, VIC20, PET, PLUS4 and CBM-II emulator.
description: |
    VICE, the multi-platform C64, C128, VIC20, PET, PLUS4 and CBM-II emulator.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(cairo)
    - pkgconfig(flac)
    - pkgconfig(gl)
    - pkgconfig(glew)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libavcodec)
    - pkgconfig(libmpg123)
    - pkgconfig(libpulse)
    - pkgconfig(pango)
    - pkgconfig(portaudio-2.0)
    - pkgconfig(vorbis)
    - pkgconfig(vte-2.91)
    - pkgconfig(xaw7)
    - pkgconfig(xpm)
    - bdftopcf
    - mkfontscale
    - xa
setup      : |
    %configure --with-alsa \
               --with-pulse \
               --enable-native-gtk3ui \
               --enable-external-ffmpeg
build      : |
    %make
install    : |
    #Otherwise the it will try to build the font cache and fail epicly
    unset HOME
    %make_install
