name       : vice
version    : 2.4.32
release    : 1
source     :
    - http://pilotfiber.dl.sourceforge.net/project/vice-emu/development-releases/vice-2.4.32.tar.gz : e9896fd00ae16627b87ac63df7722d7a8ecda9095ecc909c50fa66b8daa7c304
license    : GPL-2.0
component  : games.emulator
summary    : VICE, the multi-platform C64, C128, VIC20, PET, PLUS4 and CBM-II emulator.
description: |
    VICE, the multi-platform C64, C128, VIC20, PET, PLUS4 and CBM-II emulator.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(cairo)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libavcodec)
    - pkgconfig(libmpg123)
    - pkgconfig(libpulse)
    - pkgconfig(pango)
    - pkgconfig(portaudio-2.0)
    - pkgconfig(vte-2.91)
    - pkgconfig(xaw7)
    - bdftopcf
    - mkfontdir
setup      : |
    %configure --with-alsa \
               --with-pulse \
               --enable-gnomeui3
build      : |
    %make
install    : |
    %make_install
