name       : vice
version    : '3.1'
release    : 4
source     :
    - http://sourceforge.net/projects/vice-emu/files/releases/vice-3.1.tar.gz : 3eb8159633816095006dec36c5c3edd055a87fd8bda193a1194a6801685d1240
license    : GPL-2.0-or-later
component  : games.emulator
summary    : VICE, the multi-platform C64, C128, VIC20, PET, PLUS4 and CBM-II emulator.
description: |
    VICE, the multi-platform C64, C128, VIC20, PET, PLUS4 and CBM-II emulator.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(cairo)
    - pkgconfig(flac)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libavcodec)
    - pkgconfig(libmpg123)
    - pkgconfig(libpulse)
    - pkgconfig(pango)
    - pkgconfig(portaudio-2.0)
    - pkgconfig(vorbis)
    - pkgconfig(vte-2.91)
    - pkgconfig(xaw7)
    - pkgconfig(xpm)
    - bdftopcf
    - mkfontdir
setup      : |
    %configure --with-alsa \
               --with-pulse \
               --enable-gnomeui3 \
               --enable-external-ffmpeg
build      : |
    %make
install    : |
    #Otherwise the it will try to build the font cache and fail epicly
    unset HOME
    %make_install
