name       : vice
version    : 3.6.1
release    : 8
source     :
    - https://sourceforge.net/projects/vice-emu/files/releases/vice-3.6.1.tar.gz/download : 20df84c851aaf2f5000510927f6d31b32f269916d351465c366dc0afc9dc150c
license    : GPL-2.0-or-later
component  : games.emulator
summary    : VICE, the multi-platform C64, C128, VIC20, PET, PLUS4 and CBM-II emulator.
description: |
    VICE, the multi-platform C64, C128, VIC20, PET, PLUS4 and CBM-II emulator.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(cairo)
    - pkgconfig(flac)
    - pkgconfig(gl)
    - pkgconfig(glew)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libavcodec)
    - pkgconfig(libmpg123)
    - pkgconfig(libpulse)
    - pkgconfig(pango)
    - pkgconfig(portaudio-2.0)
    - pkgconfig(vorbis)
    - pkgconfig(vte-2.91)
    - pkgconfig(xaw7)
    - pkgconfig(xpm)
    - bdftopcf
    - dos2unix
    - mkfontscale
    - xa
setup      : |
    %configure --with-alsa \
               --with-flac \
               --with-mpg123 \
               --with-pulse \
               --with-vorbis \
               --enable-midi \
               --enable-native-gtk3ui \
               --enable-external-ffmpeg \
               --disable-pdf-docs
build      : |
    %make
install    : |
    #Otherwise the it will try to build the font cache and fail epicly
    unset HOME
    %make_install
